### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by dywsjtu** [ByronPan/ReDR#2]
When I was running the train.py, the following error occurs. 

 (base) PS D:\ReDR> python train.py -data data/coqa-cqg -save_model out_model/
[2019-08-20 23:20:28,297 INFO]  * src vocab size = 49766
[2019-08-20 23:20:28,298 INFO]  * history vocab size = 49766
[2019-08-20 23:20:28,298 INFO]  * tgt vocab size = 49766
[2019-08-20 23:20:28,299 INFO] Building model...
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(opt)
  File "train.py", line 41, in main
    single_main(opt, -1)
  File "D:\ReDR\onmt\train_single.py", line 86, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "D:\ReDR\onmt\model_builder.py", line 235, in build_model
    vocab = torch.load(opt.drqa_vocab_path)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'drqa_param\\vocab.pt'

**Comment by ByronPan** [comment]
Thanks for your attention! We have fixed this in the README.
